banner_apis/account/urls.py
from django.urls import path, include
from account.views import * #serRegistrationView,AdminBannerModelViewSet UserLoginView, UserLogoutView,CategoryModelViewSet
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'category', CategoryModelViewSet)
router.register(r'admin_banners', AdminBannerModelViewSet)

urlpatterns = [
    #user
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('validate_otp/', ValidateOTP.as_view()),
    path('getalluser/', UserRegistrationView.as_view(), name='getalluser'),
    path('updateuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='updateuser'),
    path('getuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='getuser'),
    path('deleteuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='deleteuser'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('resend-otp/', ResendUserOtpAPIView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('reset-password/', ResetPasswordAPIView.as_view(), name='reset-password'),
    #banner   
    path('add_banners/', BanerAPIView.as_view(), name='addbanner'),
    path('category_banners/<int:category_id>/', GetCategoryBanners.as_view(), name='addbanner'),
    path('get_all_banners/', BanerAPIView.as_view(), name='getalluser'),
    path('get_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='get_banner'),
    path('update_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='updatebanner'),
    path('delete_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='deletebanner'),
    
    #category
    path('', include(router.urls)),
    
    

]

banner_apis/banner_apis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('user_account/', include('user_account.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

banner_apis/user_account/urls.py
from django.urls import path
from . import views

app_name = "frontend"


urlpatterns = [
    # path('', views.home, name='home'),
    path("login/",views.Login,name="login"),
    path("logout/",views.Logout,name="logout"),

    path("user-dashbaord/",views.Dashboard,name="dashboard"),
    path("show-project/",views.ShowProject,name="showproject"),
    path("add-project/",views.AddProject,name="addproject"),
    path("update-project/<int:id>/",views.AddProject,name="updateproject"),
    path("delete-project/<int:id>/",views.DeleteProject,name="deleteproject"),

    path("show-task/",views.ShowTask,name="showtask"),
    path("add-task/",views.AddTask,name="addtask"),
    # path("update-task/<int:pk>/",views.AddTask,name="updatetask"),
    # path("delete-task/<int:pk>/",views.DeleteTask,name="deletetask"),

    path("add-employee/",views.AddEmployee,name="addemployee"),
    path("update-employee/<int:id>/",views.AddEmployee,name="updateemployee"),
    path("delete-employee/<int:id>/",views.DeleteEmployee,name="deleteemployee"),
    path("show-employee/",views.ShowEmployee,name="showemployee"),

    path("user-profile/",views.UserProfile,name="userprofile"),

    path("all-images/",views.All_imgage,name="image"),
    path("update-images/<int:id>/",views.All_imgage,name="updateimage"),
    path("delete-img/<int:id>/",views.DeleteImage,name="deleteimg"),

    path('search/', views.search_view, name='search'),

    


]

banner_apis/user_account/models.py
from django.db import models

# Create your models here.

banner_apis/user_account/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponse,redirect
from django.contrib import messages
from account.models import *
import requests
from django.core.paginator import Paginator
from account.models import *
from django.db.models import Q
from account.serializers import * 
from django.core import serializers
from django.http import JsonResponse
from rest_framework.permissions import IsAuthenticated,IsAdminUser
from rest_framework.authentication import TokenAuthentication
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

# def home(request):
#     return render(request, 'login.html')

# @login_required
def Login(request):
    
    if request.method != "POST":
        return render(request,"login.html")
    
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")


        url = 'http://0.0.0.0:8980/login/'
        data = {
            'username': username,
            'password': password,
        }
        headers = {
            # 'Content-Type': 'application/json',
            # 'Authorization': 'Token 11b79bad0061bfce54de464fd34ff7934d12f2fc',
        }

        response = requests.post(url, json=data, headers=headers)
        data = response.json()
        if response.status_code == 200:
            user_id = data['user_id']
            print(user_id)

            user = User.objects.get(id=user_id)
            is_admin = user.is_staff
        
        print(data,">>>>>>>>>>..............")



    if response.status_code == 200 and is_admin : 
        access_token= data['token']
        request.session['access_token'] = access_token
        request.session['username'] = username
        request.session['password'] = password
        
        return redirect("frontend:dashboard")
    

        # Handle successful response
        pass
    elif response.status_code == 404:
        messages.error(request,"Data is not valid. Please try again",extra_tags="error")
    else:
        # Handle error response
        pass
   
    messages.error(request,"Data is not valid. Please try again",extra_tags="error")
    return redirect("frontend:login")

def Dashboard(request):
    total_category = Category_db.objects.all().count()
    total_banner = banner_db.objects.all().count()
    total_user = User.objects.all().count()

    print(total_category,total_banner,total_user,">><<<<<")
    # if "id" not in request.session or "email" not in request.session or "type" not in request.session:
    #     messages.error(request,"Login first and then try again",extra_tags="error")
    context = {"total_category":total_category,"total_banner":total_banner,"total_user":total_user}
    return render(request,"userpages/dashboard.html",context)

def Logout(request):
    access_token = request.session.get('access_token', None)
    username = request.session.get('username', None)
    password = request.session.get('password', None)

    print(username,password,"<><><><>")

    url = 'http://0.0.0.0:8980/logout/'
    data = {
        "username":username,
        "password":password
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.post(url, json=data, headers=headers)
    request.session.clear()
    return redirect("frontend:login")

def ShowProject(request):
    url = 'http://0.0.0.0:8980/category/'
    access_token = request.session.get('access_token', None) 
    data = {
       
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.get(url, json=data, headers=headers)
    if 'q' in request.GET:
        q = request.GET['q']
        print("i am in q",q)
        all_project_data = Category_db.objects.filter(name__icontains=q)
        print("all_project_data",all_project_data)
        # return redirect("frontend:showproject")
    # if response.status_code == 200:
    #     response_data = response.json()
    #     all_project_data = response_data['results']
    else:
        # pass
        # response_data = response.json()
        # all_project_data = response_data['results']
        all_project_data = Category_db.objects.all()

    
    paginator=Paginator(all_project_data,5)
    page_number = request.GET.get('page')
    obj_data = paginator.get_page(page_number)
    totalpage = obj_data.paginator.num_pages
    context ={"all_project_data":obj_data,"lastpage":totalpage,"totalpagenumber":[n+1 for n in range(totalpage)]}
    return render(request,"userpages/showproject.html",context)

def search_view(request):
    # Get search parameters from request
    search_term = request.GET.get('q')
    
    # Query the database for products matching the search term
    products = Category_db.objects.filter(name__icontains=search_term)
    
    # Serialize the search results into JSON
    # serializer = CategorySerializer(products)
    # user = User.objects.get(id=user_id)
    # serializer = UserProfileSerializer(user)
    # return Response(serializer.data,status=200)
    data = serializers.serialize('json', products)
    # Return the search results as JSON response
    return JsonResponse(data, safe=False)


def AddProject(request,id=0):
    name = request.GET.get('name', '')
    access_token = request.session.get('access_token', None) 
    print("~~~~~~~~~~~~~~>>>>>>",id)
    
    if id==0:
        if request.method == "POST":

            name = request.POST.get("name")
    

            url = 'http://0.0.0.0:8980/category/'
            data = {
                'name': name,
            }
            headers = {
                'Content-Type': 'application/json',
                'Authorization': f'Token {access_token}',
            }

            response = requests.post(url, json=data, headers=headers)
            all_project_data = response.json()
            # print(response,"~~~~~~~~~~~~~")
            messages.success(request,"Data added.",extra_tags="success")
            return redirect("frontend:showproject")
        
    else:
       

        if request.method == "POST":
            name = request.POST.get("name")
            url = f'http://0.0.0.0:8980/category/{id}/'
            data = {
                'name': name,
            }
            headers = {
                'Content-Type': 'application/json',
               'Authorization': f'Token {access_token}',
            }
            response = requests.put(url, json=data, headers=headers)
            messages.success(request,"Data Update.",extra_tags="success")
            update_data = response.json()
            return redirect("frontend:showproject")
        context = {"id":id,"name":name}
        return render(request,"userpages/addproject.html",context)

    return render(request,"userpages/addproject.html")

def Updateproject(request,id=0):

    print(id,"~~~~~~~~~~~~~~>>>>>>")
    return render(request,"userpages/showproject.html")

def DeleteProject(request,id):
    access_token = request.session.get('access_token', None) 
    url = f'http://0.0.0.0:8980/category/{id}/'
    data = {

    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.delete(url, json=data, headers=headers)

    messages.success(request,"Your file has been deleted.",extra_tags="deletesuccess")
    return redirect("frontend:showproject")

def ShowTask(request):

    obj = banner_db.objects.all()
    access_token = request.session.get('access_token', None) 
    url = 'http://0.0.0.0:8980/get_all_banners/'
    data = {
       
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.get(url, json=data, headers=headers)
    all_task_data = response.json()
    d = all_task_data['data']
    # for i in d:
    # print(all_task_data['data'])
    my_list = all_task_data['data']
    templates_string = ''
    for dictionary in my_list:
        if dictionary.get('templates'):
            # print("i am for >>>>>",dictionary['templates'])
            templates_string += ', '.join(dictionary['templates'])


    obj = banner_db.objects.all()
    category_ids = [item.category_id for item in obj]
    unique_category_ids = list(set(category_ids))
    category_names = [Category_db.objects.get(id=id).name for id in unique_category_ids]
    print(category_names,"????????????????")
    if 'q' in request.GET:
        query = request.GET['q']
        # query = "demo" # replace with your search query
        category_names = [name for name in category_names if query.lower() in name.lower()]

    paginator=Paginator(category_names,5)
    page_number = request.GET.get('page')
    obj_data = paginator.get_page(page_number)
    totalpage = obj_data.paginator.num_pages
    context ={"all_task_data":obj_data,"lastpage":totalpage,"totalpagenumber":[n+1 for n in range(totalpage)]}
    return render(request,"userpages/showtask.html",context)

def AddTask(request,pk=0):
    obj = Category_db.objects.all()
    
    if request.method == "POST":
        category = request.POST.get('category_id')
        banner = request.FILES.get('banner_img')
        print("KJJJJJJJJJJJJJJJJJJJ",category)
        banner_obj = banner_db(banner_img=banner,category_id =category)
        banner_obj.save()
       
        messages.success(request,"Data added.",extra_tags="success")
        
        return redirect("frontend:showtask")
        
    
    context ={"all_task_data":obj}
    return render(request,"userpages/addtask.html",context)

def All_imgage(request, id=0):

    name = request.GET.get('id')
    
    if id !=0:
        banner_obj = banner_db.objects.get(id=id)
        print(banner_obj.category_id,">>>>>>>>>>>>>>>>>>>>>>>>")
        obj = Category_db.objects.filter(id=banner_obj.category_id).all()

banner_apis/user_account/templates/userpages/banner.html
<!-- <!DOCTYPE html>
<html>

<head>
    <title>Multiple Images</title>
</head>

<body> -->

<!-- <div class="card">
        <div class="card-body">

            <div class="row">
                <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
                    {% for i in data %}
                <img
                    src="{{i.banner_img}}"
                    class="img-responsive"
                    alt="Boat on Calm Water"
                    width="307" height="240"/
                />
            {% endfor %}
            
                </div>
            </div>
        </div>
    </div> -->

<!-- <div class="card">
        <div class="card-body">
            <div class="d-sm-flex justify-content-between align-items-start">
                <div>
                    <h4 class="card-title card-title-dash">User Data</h4>

                </div>
                <div>
                    <a href="{% url 'frontend:addemployee' %}"><button type="button"
                            class="btn btn-outline-info btn-rounded btn-icon btn-sm">Add New
                            <i class="mdi mdi-account-plus"></i>
                        </button></a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th>
                            <tr>Category</tr>
                        </th>
                    </thead>
                    <tbody>
                        {% for i in data %}
                        <tr>
                            <td>{{i.banner_img}}</td>
                            <td>
                                <a href="{% url 'frontend:updateemployee' i.id  %}?username={{ i.username }}email={{i.email}}""><button type="
                                    button" class="btn btn-outline-success btn-icon-text btn-sm"> Edit<i
                                        class="mdi mdi-tooltip-edit btn-icon-append"></i></button></a>

                                <a id="callapi" href="{% url 'frontend:deleteemployee' i.id %}">
                                    <button type="button"
                                        class="btn btn-outline-danger btn-icon-text btn-sm kt_sweetalert_demo_6">
                                        Delete<i class="mdi mdi-delete btn-icon-delete"> </i></button></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>


        </div>

</body>

</html> -->

<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'userpages/basic/head.html' %}
    <link rel="stylesheet" href="/static/mycss.css">
</head>

<body>
    <div class="container-scroller">
        {% include 'userpages/basic/nav.html' %}
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            {% include 'userpages/basic/sidebar.html' %}
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-lg-12 grid-margin stretch-card">
                            <div class="card">
                                <div class="card-body">
                                    <div class="d-sm-flex justify-content-between align-items-start">
                                        <div>
                                            <h4 class="card-title card-title-dash">Banner Data</h4>

                                        </div>
                                        <div>
                                            <a href="{% url 'frontend:addtask' %}"><button type="button"
                                                    class="btn btn-outline-info btn-rounded btn-icon btn-sm">Add New
                                                    <i class="mdi mdi-account-plus"></i>
                                                </button></a>
                                        </div>
                                    </div>
                                    <div class="table-responsive">

                                        <table>
                                            <thead>
                                                <th>
                                                    <tr>Banner's</tr>
                                                </th>
                                            </thead>
                                            <tbody>

                                                <div class="row">
                                                    {% for i in data %}

                                                    <div class="col">
                                                        <div class="card" style="width: 18rem ">
                                                            <img class="card-img-top" src="{{i.banner_img}}"
                                                                alt="Card image cap">
                                                            <div class="card-body">
                                                                <a href="{% url 'frontend:updateimage' i.id  %}"
                                                                    class="btn btn-primary">Edit</a>
                                                                <a href="{% url 'frontend:deleteimg' i.id %}"
                                                                    class="btn btn-danger">Delete</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    {% endfor %}

                                                </div>


                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- content-wrapper ends -->
                    <!-- partial:partials/_footer.html -->
                    {% include 'userpages/basic/footer.html' %}
                    <!-- partial -->
                </div>
                <!-- main-panel ends -->
            </div>
            <!-- page-body-wrapper ends -->
        </div>
        <!-- container-scroller -->

        {% include 'userpages/basic/js_script.html' %}
        {% if messages %}
        {% for message in messages %}

        {% if message.extra_tags == 'deletesuccess' %}
        <script>Swal.fire("Deleted!", "{{message}}", "success")</script>

        {% elif message.extra_tags == 'deleteerror' %}
        <script>Swal.fire("Not Deleted!", "{{message}}", "error")</script>
        {% else %}

        <script>
            Swal.fire({
                position: "top-end",
                type: `{{message.extra_tags}}`,
                title: `{{ message }}`,
                showConfirmButton: !1,
                timer: 1500
            })
        </script>

        {% endif %}
        {% endfor %}
        {% endif %}

        <!-- <script>
      $(".kt_sweetalert_demo_6").click(function (e) {
        Swal.fire({
          title: "Are you sure?",
          text: "You won't be able to revert this!",
          type: "warning",
          showCancelButton: !0,
          confirmButtonColor: "#34c38f",
          cancelButtonColor: "#f46a6a",
          confirmButtonText: "Yes, delete it!"
        }).then(function (t) {
          // $('#callapi').click();
          location.href = $('#callapi').attr('href');
        })

      })
    </script> -->

        <!-- Swal.fire("Deleted!", "Your file has been deleted.", "success")  -->
</body>

</html>

banner_apis/user_account/templates/userpages/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'userpages/basic/head.html' %}
    <link rel="stylesheet" href="/static/mycss.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    
    <section class="vh-100" style="background-color: #f4f5f7;">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col col-lg-6 mb-4 mb-lg-0">
            <div class="card mb-3" style="border-radius: .5rem;">
              <div class="row g-0">
                <div class="col-md-4 gradient-custom text-center text-white"
                  style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
                  <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                    alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
                  <h5>Marie Horwitz</h5>
                  <p>Web Designer</p>
                  <i class="far fa-edit mb-5"></i>
                </div>
                <div class="col-md-8">
                  <div class="card-body p-4">
                    <h6>Information</h6>
                    <hr class="mt-0 mb-4">
                    <div class="row pt-1">
                      <div class="col-6 mb-3">
                        <h6>Email</h6>
                        <p class="text-muted">info@example.com</p>
                      </div>
                      <div class="col-6 mb-3">
                        <h6>Phone</h6>
                        <p class="text-muted">123 456 789</p>
                      </div>
                    </div>
                    <h6>Projects</h6>
                    <hr class="mt-0 mb-4">
                    <div class="row pt-1">
                      <div class="col-6 mb-3">
                        <h6>Recent</h6>
                        <p class="text-muted">Lorem ipsum</p>
                      </div>
                      <div class="col-6 mb-3">
                        <h6>Most Viewed</h6>
                        <p class="text-muted">Dolor sit amet</p>
                      </div>
                    </div>
                    <div class="d-flex justify-content-start">
                      <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                      <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                      <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                    </div>
                  </div>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </section>

</body>

</html>

banner_apis/user_account/templates/userpages/showemployee.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% include 'userpages/basic/head.html' %}
  <link rel="stylesheet" href="/static/mycss.css">
</head>

<body>
  <div class="container-scroller">
    {% include 'userpages/basic/nav.html' %}
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      {% include 'userpages/basic/sidebar.html' %}
      <div class="main-panel">
        <div class="content-wrapper">
          <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
              <div class="card">
                <div class="card-body">
                  <div class="d-sm-flex justify-content-between align-items-start">
                    <div>
                      <h4 class="card-title card-title-dash">User Data</h4>
                      
                    </div>
                    <div>
                      <!-- right side for  -->
                      <a href="{% url 'frontend:addemployee' %}"><button type="button"
                          class="btn btn-outline-info btn-rounded btn-icon btn-sm">Add New
                          <i class="mdi mdi-account-plus"></i>
                        </button></a>
                    </div>
                  </div>
                  <div class="table-responsive">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>Username</th>
                          <th>Email</th>
                          <th>Full Name</th>
                          <th>Mobile</th>
                          <th>Profile Image</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for i in all_emp_data %}
                        <tr>
                          <td>{{i.username}} </td>
                          <td>{{i.email}}</td>
                          <td>{{i.full_name}}</td>
                          <td>{{i.phone_number}}</td> 
                          <td><img src="{{i.profilei_image}}" class="img-responsive"
                            alt="user" width="307" height="240"
                            style="display:ruby-base-container;" /></td>

                          <td>
                            <a href="{% url 'frontend:updateemployee' i.id  %}?username={{ i.username }}email={{i.email}}""><button type="button"
                                class="btn btn-outline-success btn-icon-text btn-sm"> Edit<i
                                  class="mdi mdi-tooltip-edit btn-icon-append"></i></button></a>

                            <a id="callapi" href="{% url 'frontend:deleteemployee' i.id %}">
                              <button type="button" class="btn btn-outline-danger btn-icon-text btn-sm kt_sweetalert_demo_6"> Delete<i 
                                class="mdi mdi-delete btn-icon-delete"> </i></button></a>
                          </td>                   
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
                <nav aria-label="Page navigation example" style="margin-left: 70%;" >
                  <ul class="pagination">
                    {% if all_emp_data.has_previous %}
                    <li class="page-item"><a class="page-link" href="/user_account/show-employee/?page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="/user_account/show-task/?page={{all_task_data.previous_page_number}}">Previous</a></li>

                    {%endif%}
                    {% for n in totalpagenumber %}
                    <li class="page-item"><a class="page-link" href="/user_account/show-employee/?page={{n}}">{{n}}</a></li>
                    {% endfor %}
                    {% if all_emp_data.has_next %}
                    <li class="page-item"><a class="page-link" href="/user_account/show-employee/?page={{lastpage}}">Last</a></li>

                    <li class="page-item"><a class="page-link" href="/user_account/show-employee/?page={{all_emp_data.next_page_number}}">Next</a></li>
                    {%endif%}
                  </ul>
                </nav>
                </div>
                
              </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
          <!-- partial:partials/_footer.html -->
          {% include 'userpages/basic/footer.html' %}
          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
      
    
    <!-- container-scroller -->

    {% include 'userpages/basic/js_script.html' %}
    {% if messages %}
    {% for message in messages %}

    {% if message.extra_tags == 'deletesuccess' %}
    <script>Swal.fire("Deleted!", "{{message}}", "success")</script>

    {% elif message.extra_tags == 'deleteerror' %}
    <script>Swal.fire("Not Deleted!", "{{message}}", "error")</script>
    {% else %}

    <script>
      Swal.fire({
        position: "top-end",
        type: `{{message.extra_tags}}`,
        title: `{{ message }}`,
        showConfirmButton: !1,
        timer: 1500
      })
    </script>

    {% endif %}
    {% endfor %}
    {% endif %}

    <!-- <script>
      $(".kt_sweetalert_demo_6").click(function (e) {
        Swal.fire({
          title: "Are you sure?",
          text: "You won't be able to revert this!",
          type: "warning",
          showCancelButton: !0,
          confirmButtonColor: "#34c38f",
          cancelButtonColor: "#f46a6a",
          confirmButtonText: "Yes, delete it!"
        }).then(function (t) {
          // $('#callapi').click();
          location.href = $('#callapi').attr('href');
        })

      })
    </script> -->

    <!-- Swal.fire("Deleted!", "Your file has been deleted.", "success")  -->
</body>

</html>