banner_apis/account/urls.py
from django.urls import path, include
from account.views import * #serRegistrationView,AdminBannerModelViewSet UserLoginView, UserLogoutView,CategoryModelViewSet
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'category', CategoryModelViewSet)
router.register(r'admin_banners', AdminBannerModelViewSet)

urlpatterns = [
    #user
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('validate_otp/', ValidateOTP.as_view()),
    path('getalluser/', UserRegistrationView.as_view(), name='getalluser'),
    path('updateuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='updateuser'),
    path('getuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='getuser'),
    path('deleteuser/<int:id>/', UserRetrieveUpdateDestroyAPIView.as_view(), name='deleteuser'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('resend-otp/', ResendUserOtpAPIView.as_view(), name='change-password'),
    path('user-profile/', UserProfileAPIView.as_view(), name='user-profile'),
    path('reset-password/', ResetPasswordAPIView.as_view(), name='reset-password'),
    #banner   
    path('add_banners/', BanerAPIView.as_view(), name='addbanner'),
    path('category_banners/<int:category_id>/', GetCategoryBanners.as_view(), name='addbanner'),
    path('get_all_banners/', BanerAPIView.as_view(), name='getalluser'),
    path('get_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='get_banner'),
    path('update_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='updatebanner'),
    path('delete_banner/<int:id>/', BannerRetrieveUpdateDestroyAPIView.as_view(), name='deletebanner'),
    
    #category
    path('', include(router.urls)),
    
    

]

banner_apis/banner_apis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('user_account/', include('user_account.urls'))

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

banner_apis/user_account/urls.py
from django.urls import path
from . import views

app_name = "frontend"


urlpatterns = [
    # path('', views.home, name='home'),
    path("login/",views.Login,name="login"),
    path("logout/",views.Logout,name="logout"),

    path("user-dashbaord/",views.Dashboard,name="dashboard"),
    path("show-project/",views.ShowProject,name="showproject"),
    path("add-project/",views.AddProject,name="addproject"),
    path("update-project/<int:id>/",views.AddProject,name="updateproject"),
    path("delete-project/<int:id>/",views.DeleteProject,name="deleteproject"),

    path("show-task/",views.ShowTask,name="showtask"),
    path("add-task/",views.AddTask,name="addtask"),
    # path("update-task/<int:pk>/",views.AddTask,name="updatetask"),
    # path("delete-task/<int:pk>/",views.DeleteTask,name="deletetask"),

    path("add-employee/",views.AddEmployee,name="addemployee"),
    path("update-employee/<int:id>/",views.AddEmployee,name="updateemployee"),
    path("delete-employee/<int:id>/",views.DeleteEmployee,name="deleteemployee"),
    path("show-employee/",views.ShowEmployee,name="showemployee"),

    path("user-profile/",views.UserProfile,name="userprofile"),

    path("all-images/",views.All_imgage,name="image"),
    path("update-images/<int:id>/",views.All_imgage,name="updateimage"),
    path("delete-img/<int:id>/",views.DeleteImage,name="deleteimg"),

    path('search/', views.search_view, name='search'),

    


]

banner_apis/user_account/models.py
from django.db import models

# Create your models here.

banner_apis/user_account/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponse,redirect
from django.contrib import messages
from account.models import *
import requests
from django.core.paginator import Paginator
from account.models import *
from django.db.models import Q
from account.serializers import * 
from django.core import serializers
from django.http import JsonResponse
from rest_framework.permissions import IsAuthenticated,IsAdminUser
from rest_framework.authentication import TokenAuthentication
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

# def home(request):
#     return render(request, 'login.html')

# @login_required
def Login(request):
    
    if request.method != "POST":
        return render(request,"login.html")
    
    else:
        username = request.POST.get("username")
        password = request.POST.get("password")


        url = 'http://0.0.0.0:8980/login/'
        data = {
            'username': username,
            'password': password,
        }
        headers = {
            # 'Content-Type': 'application/json',
            # 'Authorization': 'Token 11b79bad0061bfce54de464fd34ff7934d12f2fc',
        }

        response = requests.post(url, json=data, headers=headers)
        data = response.json()
        if response.status_code == 200:
            user_id = data['user_id']
            print(user_id)

            user = User.objects.get(id=user_id)
            is_admin = user.is_staff
        
        print(data,">>>>>>>>>>..............")



    if response.status_code == 200 and is_admin : 
        access_token= data['token']
        request.session['access_token'] = access_token
        request.session['username'] = username
        request.session['password'] = password
        
        return redirect("frontend:dashboard")
    

        # Handle successful response
        pass
    elif response.status_code == 404:
        messages.error(request,"Data is not valid. Please try again",extra_tags="error")
    else:
        # Handle error response
        pass
   
    messages.error(request,"Data is not valid. Please try again",extra_tags="error")
    return redirect("frontend:login")

def Dashboard(request):
    total_category = Category_db.objects.all().count()
    total_banner = banner_db.objects.all().count()
    total_user = User.objects.all().count()

    print(total_category,total_banner,total_user,">><<<<<")
    # if "id" not in request.session or "email" not in request.session or "type" not in request.session:
    #     messages.error(request,"Login first and then try again",extra_tags="error")
    context = {"total_category":total_category,"total_banner":total_banner,"total_user":total_user}
    return render(request,"userpages/dashboard.html",context)

def Logout(request):
    access_token = request.session.get('access_token', None)
    username = request.session.get('username', None)
    password = request.session.get('password', None)

    print(username,password,"<><><><>")

    url = 'http://0.0.0.0:8980/logout/'
    data = {
        "username":username,
        "password":password
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.post(url, json=data, headers=headers)
    request.session.clear()
    return redirect("frontend:login")

def ShowProject(request):
    url = 'http://0.0.0.0:8980/category/'
    access_token = request.session.get('access_token', None) 
    data = {
       
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.get(url, json=data, headers=headers)
    if 'q' in request.GET:
        q = request.GET['q']
        print("i am in q",q)
        all_project_data = Category_db.objects.filter(name__icontains=q)
        print("all_project_data",all_project_data)
        # return redirect("frontend:showproject")
    # if response.status_code == 200:
    #     response_data = response.json()
    #     all_project_data = response_data['results']
    else:
        # pass
        # response_data = response.json()
        # all_project_data = response_data['results']
        all_project_data = Category_db.objects.all()

    
    paginator=Paginator(all_project_data,5)
    page_number = request.GET.get('page')
    obj_data = paginator.get_page(page_number)
    totalpage = obj_data.paginator.num_pages
    context ={"all_project_data":obj_data,"lastpage":totalpage,"totalpagenumber":[n+1 for n in range(totalpage)]}
    return render(request,"userpages/showproject.html",context)

def search_view(request):
    # Get search parameters from request
    search_term = request.GET.get('q')
    
    # Query the database for products matching the search term
    products = Category_db.objects.filter(name__icontains=search_term)
    
    # Serialize the search results into JSON
    # serializer = CategorySerializer(products)
    # user = User.objects.get(id=user_id)
    # serializer = UserProfileSerializer(user)
    # return Response(serializer.data,status=200)
    data = serializers.serialize('json', products)
    # Return the search results as JSON response
    return JsonResponse(data, safe=False)


def AddProject(request,id=0):
    name = request.GET.get('name', '')
    access_token = request.session.get('access_token', None) 
    print("~~~~~~~~~~~~~~>>>>>>",id)
    
    if id==0:
        if request.method == "POST":

            name = request.POST.get("name")
    

            url = 'http://0.0.0.0:8980/category/'
            data = {
                'name': name,
            }
            headers = {
                'Content-Type': 'application/json',
                'Authorization': f'Token {access_token}',
            }

            response = requests.post(url, json=data, headers=headers)
            all_project_data = response.json()
            # print(response,"~~~~~~~~~~~~~")
            messages.success(request,"Data added.",extra_tags="success")
            return redirect("frontend:showproject")
        
    else:
       

        if request.method == "POST":
            name = request.POST.get("name")
            url = f'http://0.0.0.0:8980/category/{id}/'
            data = {
                'name': name,
            }
            headers = {
                'Content-Type': 'application/json',
               'Authorization': f'Token {access_token}',
            }
            response = requests.put(url, json=data, headers=headers)
            messages.success(request,"Data Update.",extra_tags="success")
            update_data = response.json()
            return redirect("frontend:showproject")
        context = {"id":id,"name":name}
        return render(request,"userpages/addproject.html",context)

    return render(request,"userpages/addproject.html")

def Updateproject(request,id=0):

    print(id,"~~~~~~~~~~~~~~>>>>>>")
    return render(request,"userpages/showproject.html")

def DeleteProject(request,id):
    access_token = request.session.get('access_token', None) 
    url = f'http://0.0.0.0:8980/category/{id}/'
    data = {

    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.delete(url, json=data, headers=headers)

    messages.success(request,"Your file has been deleted.",extra_tags="deletesuccess")
    return redirect("frontend:showproject")

def ShowTask(request):

    obj = banner_db.objects.all()
    access_token = request.session.get('access_token', None) 
    url = 'http://0.0.0.0:8980/get_all_banners/'
    data = {
       
    }
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Token {access_token}',
    }

    response = requests.get(url, json=data, headers=headers)
    all_task_data = response.json()
    d = all_task_data['data']
    # for i in d:
    # print(all_task_data['data'])
    my_list = all_task_data['data']
    templates_string = ''
    for dictionary in my_list:
        if dictionary.get('templates'):
            # print("i am for >>>>>",dictionary['templates'])
            templates_string += ', '.join(dictionary['templates'])


    obj = banner_db.objects.all()
    category_ids = [item.category_id for item in obj]
    unique_category_ids = list(set(category_ids))
    category_names = [Category_db.objects.get(id=id).name for id in unique_category_ids]
    print(category_names,"????????????????")
    if 'q' in request.GET:
        query = request.GET['q']
        # query = "demo" # replace with your search query
        category_names = [name for name in category_names if query.lower() in name.lower()]

    paginator=Paginator(category_names,5)
    page_number = request.GET.get('page')
    obj_data = paginator.get_page(page_number)
    totalpage = obj_data.paginator.num_pages
    context ={"all_task_data":obj_data,"lastpage":totalpage,"totalpagenumber":[n+1 for n in range(totalpage)]}
    return render(request,"userpages/showtask.html",context)

def AddTask(request,pk=0):
    obj = Category_db.objects.all()
    
    if request.method == "POST":
        category = request.POST.get('category_id')
        banner = request.FILES.get('banner_img')
        print("KJJJJJJJJJJJJJJJJJJJ",category)
        banner_obj = banner_db(banner_img=banner,category_id =category)
        banner_obj.save()
       
        messages.success(request,"Data added.",extra_tags="success")
        
        return redirect("frontend:showtask")
        
    
    context ={"all_task_data":obj}
    return render(request,"userpages/addtask.html",context)

def All_imgage(request, id=0):

    name = request.GET.get('id')
    
    if id !=0:
        banner_obj = banner_db.objects.get(id=id)
        print(banner_obj.category_id,">>>>>>>>>>>>>>>>>>>>>>>>")
        obj = Category_db.objects.filter(id=banner_obj.category_id).all()

banner_apis/user_account/templates/userpages/basic/footer.html
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
      <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Premium <a href="#" target="_blank">Admin Banner Site</a> from Koli Infotech.</span>
      <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2022. All rights reserved.</span>
    </div>
  </footer>

banner_apis/user_account/templates/userpages/basic/head.html
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Banner</title>
<!-- plugins:css -->
<link rel="stylesheet" href="/static/vendors/feather/feather.css">
<link rel="stylesheet" href="/static/vendors/mdi/css/materialdesignicons.min.css">
<link rel="stylesheet" href="/static/vendors/ti-icons/css/themify-icons.css">
<link rel="stylesheet" href="/static/vendors/typicons/typicons.css">
<link rel="stylesheet" href="/static/vendors/simple-line-icons/css/simple-line-icons.css">
<link rel="stylesheet" href="/static/vendors/css/vendor.bundle.base.css">
<!-- endinject -->
<!-- Plugin css for this page -->
<link rel="stylesheet" href="/static/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
<link rel="stylesheet" href="/static/js/select.dataTables.min.css">
<!-- End plugin css for this page -->
<!-- inject:css -->
<link rel="stylesheet" href="/static/css/vertical-layout-light/style.css">
<!-- endinject -->
<link rel="shortcut icon" href="/static/images/favicon.png" />
<link rel="stylesheet" href="/static/alert/sweetalert2.min.css">

banner_apis/user_account/templates/userpages/basic/js_script.html
<!-- plugins:js -->
<script src="/static/vendors/js/vendor.bundle.base.js"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="/static/vendors/chart.js/Chart.min.js"></script>
<script src="/static/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="/static/vendors/progressbar.js/progressbar.min.js"></script>

<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="/static/js/off-canvas.js"></script>
<script src="/static/js/hoverable-collapse.js"></script>
<script src="/static/js/template.js"></script>
<script src="/static/js/settings.js"></script>
<script src="/static/js/todolist.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="/static/js/dashboard.js"></script>
<script src="/static/js/Chart.roundedBarCharts.js"></script>
<!-- End custom js for this page-->

<script src="/static/alert/sweetalert2.min.js"></script>
<script src="/static/alert/sweet-alerts.init.js"></script>

banner_apis/user_account/templates/userpages/basic/nav.html
<!-- partial:partials/_navbar.html -->
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
      <div class="me-3">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
          <span class="icon-menu"></span>
        </button>
      </div>
      <div>
        <a class="navbar-brand brand-logo" href="{% url 'frontend:dashboard' %}">
          <img src="/static/images/logo.svg" alt="logo" />
        </a>
        <a class="navbar-brand brand-logo-mini" href="{% url 'frontend:dashboard' %}">
          <img src="/static/images/logo-mini.svg" alt="logo" />
        </a>
      </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-top"> 
      <ul class="navbar-nav">
        <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
          <h1 class="welcome-text">{{greeting}} <span class="text-black fw-bold">{{user.fname.title}}</span></h1>
          <h3 class="welcome-sub-text">{{pagetype}} </h3>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <!-- <li class="nav-item dropdown d-none d-lg-block">
          <a class="nav-link dropdown-bordered dropdown-toggle dropdown-toggle-split" id="messageDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false"> Select Category </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
            <a class="dropdown-item py-3" >
              <p class="mb-0 font-weight-medium float-left">Select category</p>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Bootstrap Bundle </p>
                <p class="fw-light small-text mb-0">This is a Bundle featuring 16 unique dashboards</p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Angular Bundle</p>
                <p class="fw-light small-text mb-0">Everything you’ll ever need for your Angular projects</p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">VUE Bundle</p>
                <p class="fw-light small-text mb-0">Bundle of 6 Premium Vue Admin Dashboard</p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">React Bundle</p>
                <p class="fw-light small-text mb-0">Bundle of 8 Premium React Admin Dashboard</p>
              </div>
            </a>
          </div>
        </li> -->
        <li class="nav-item d-none d-lg-block">
          <div id="datepicker-popup" class="input-group date datepicker navbar-date-picker">
            <span class="input-group-addon input-group-prepend border-right">
              <span class="icon-calendar input-group-text calendar-icon"></span>
            </span>
            <input type="text" class="form-control">
          </div>
        </li>
        <li class="nav-item">
          <form class="search-form" action="">
            <i class="icon-search"></i>
            <input type="search" class="form-control" name="q" placeholder="Search Here" title="Search here">
          </form>
        </li>
        <!-- <li class="nav-item dropdown">
          <a class="nav-link count-indicator" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
            <i class="icon-mail icon-lg"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
            <a class="dropdown-item py-3 border-bottom">
              <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
              <span class="badge badge-pill badge-primary float-right">View all</span>
            </a>
            <a class="dropdown-item preview-item py-3">
              <div class="preview-thumbnail">
                <i class="mdi mdi-alert m-auto text-primary"></i>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject fw-normal text-dark mb-1">Application Error</h6>
                <p class="fw-light small-text mb-0"> Just now </p>
              </div>
            </a>
            <a class="dropdown-item preview-item py-3">
              <div class="preview-thumbnail">
                <i class="mdi mdi-settings m-auto text-primary"></i>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject fw-normal text-dark mb-1">Settings</h6>
                <p class="fw-light small-text mb-0"> Private message </p>
              </div>
            </a>
            <a class="dropdown-item preview-item py-3">
              <div class="preview-thumbnail">
                <i class="mdi mdi-airballoon m-auto text-primary"></i>
              </div>
              <div class="preview-item-content">
                <h6 class="preview-subject fw-normal text-dark mb-1">New user registration</h6>
                <p class="fw-light small-text mb-0"> 2 days ago </p>
              </div>
            </a>
          </div>
        </li> -->
        <!-- <li class="nav-item dropdown"> 
          <a class="nav-link count-indicator" id="countDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="icon-bell"></i>
            <span class="count"></span>
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="countDropdown">
            <a class="dropdown-item py-3">
              <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
              <span class="badge badge-pill badge-primary float-right">View all</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="/static/images/faces/face10.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="/static/images/faces/face12.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="/static/images/faces/face1.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
              </div>
            </a>
          </div>
        </li> -->
        <li class="nav-item dropdown d-none d-lg-block user-dropdown">
          <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
            <img class="img-xs rounded-circle" src="/static/images/faces/face8.jpg" alt="Profile image"> </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <div class="dropdown-header text-center">
              <img class="img-md rounded-circle" src="/static/images/faces/face8.jpg" alt="Profile image">
              <p class="mb-1 mt-3 font-weight-semibold">Admin</p>
              <p class="fw-light text-muted mb-0">{{user.email}}</p>
            </div>
            <a href="{% url 'frontend:userprofile' %}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile</a>
            <a href="{% url 'frontend:logout' %}" class="dropdown-item"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
        <span class="mdi mdi-menu"></span>
      </button>
    </div>
  </nav>

banner_apis/user_account/templates/userpages/basic/sidebar.html
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'frontend:dashboard' %}">
          <i class="mdi mdi-grid-large menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#Employees" aria-expanded="false" aria-controls="Employees">
          <i class="menu-icon mdi mdi-account-circle-outline"></i>
          <span class="menu-title">Users</span>
          <i class="menu-arrow"></i> 
        </a>
        <div class="collapse" id="Employees">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:addemployee' %}">Add User</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:showemployee' %}">Show User</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#Projects" aria-expanded="false" aria-controls="Projects">
          <i class="menu-icon mdi mdi-layers-outline"></i>
          <span class="menu-title">Category</span>
          <i class="menu-arrow"></i> 
        </a>
        <div class="collapse" id="Projects">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:addproject' %}">Add Category</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:showproject' %}">Show Category</a></li>
          </ul>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-bs-toggle="collapse" href="#Task" aria-expanded="false" aria-controls="Task">
          <i class="menu-icon mdi mdi-card-text-outline"></i>
          <span class="menu-title">Banner's</span>
          <i class="menu-arrow"></i> 
        </a>
        <div class="collapse" id="Task">
          <ul class="nav flex-column sub-menu">
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:addtask' %}">Add Banner</a></li>
            <li class="nav-item"> <a class="nav-link" href="{% url 'frontend:showtask' %}">Show Banner</a></li>
          </ul>
        </div>
      </li>
      {% if request.session.type == "Admin" %}
      
      {% endif %}

      {% if request.session.type == "Admin" or request.session.type == "Project Manager" %}
      

      {% endif %}
      
      {% if request.session.type == "Admin" or request.session.type == "Project Manager" or request.session.type == "Team Leader" or request.session.type == "Senior Developer" %}


      
      {% endif %}

    </ul>
  </nav>
  <!-- partial -->